### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by nkh** [kaz-utashiro/Text-ANSI-Tabs#1]
Nice work (fellow Perl dev.), this saved me the trouble of having to write it myself.

**Comment by kaz-utashiro** [comment]
My pleasure!
Other ANSI related tools are collected at https://github.com/tecolicom/ANSI-Tools .

**Comment by nkh** [comment]
seen them, between your modules and this   https://metacpan.org/pod/Text::ANSI::Util, we're quite set.

The only app/modules that I haven't found yet is something that would work like 'cut'

**Comment by kaz-utashiro** [comment]
I guess `cut` option can be translated to `ansifold` or `ansicolrm`.

```
$ echo 1234567890 | cut -c 2-5,7-9
2345789
$ echo 1234567890 | ansifold -nw -1,4,-1,3,
2345789
$ echo 1234567890 | ansicolrm 1 1 6 6 10
2345789
```

Try this to see how it works.
```
$ echo 1234567890 | greple .. --uc | tee /dev/stderr | ansifold -nw -1,4,-1,3,
```

Actually `ansicolrm` is implemented by `ansifold --colrm` option, and it may be a good idea to add `--cut` option to `ansifold`.

`ansiexpand` is also performed as `ansifold -xw-1`.

**Comment by kaz-utashiro** [comment]
https://metacpan.org/dist/App-ansifold/view/script/ansicut
